/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDarkForestTokens,
  IDarkForestTokensInterface,
} from "../IDarkForestTokens";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getArtifact",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "isInitialized",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "planetDiscoveredOn",
            type: "uint256",
          },
          {
            internalType: "enum IDarkForestTokens.ArtifactRarity",
            name: "rarity",
            type: "uint8",
          },
          {
            internalType: "enum IDarkForestTokens.Biome",
            name: "planetBiome",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "mintedAtTimestamp",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "discoverer",
            type: "address",
          },
          {
            internalType: "enum IDarkForestTokens.ArtifactType",
            name: "artifactType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "lastActivated",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastDeactivated",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "wormholeTo",
            type: "uint256",
          },
        ],
        internalType: "struct IDarkForestTokens.Artifact",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IDarkForestTokens__factory {
  static readonly abi = _abi;
  static createInterface(): IDarkForestTokensInterface {
    return new utils.Interface(_abi) as IDarkForestTokensInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDarkForestTokens {
    return new Contract(address, _abi, signerOrProvider) as IDarkForestTokens;
  }
}
